[package]
name = "starknet-crypto"
version = "0.2.0"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/xJonathanLEI/starknet-rs"
homepage = "https://starknet.rs/"
description = """
Low-level cryptography utilities for Starknet
"""
keywords = ["ethereum", "starknet", "web3"]

[dependencies]
starknet-crypto-codegen = { version = "0.1.0", path = "../starknet-crypto-codegen", default-features = false }
starknet-curve = { version = "0.1.0", path = "../starknet-curve", default-features = false }
starknet-ff = { version = "0.2.0", path = "../starknet-ff", default-features = false }
crypto-bigint = {version = "0.4.9", default-features = false}
hmac = "0.12.1"
num-bigint = {version = "0.4.3", default-features = false}
num-integer = {version = "0.1.44", default-features = false}
num-traits = {version = "0.2.15", default-features = false}
rfc6979 = "0.3.1"
sha2 = "0.10.6"
thiserror = "1.0.30"
zeroize = "1.5.0"
hex = {version = "0.4.3", default-features = false}
no-std-compat = { version = "0.4.1", features = [
    "alloc",
    "compat_macros",
    "std",
] }
[features]
default = [ "std" ] # Default to using the std
std = [ "no-std-compat/std", "starknet-crypto-codegen/std", "starknet-curve/std", "starknet-ff/std" ]

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false }
hex = {version = "0.4.3", default-features = false}
hex-literal = "0.3.4"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.74"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.29"

[[bench]]
name = "pedersen_hash"
harness = false

[[bench]]
name = "ecdsa_get_public_key"
harness = false

[[bench]]
name = "ecdsa_sign"
harness = false

[[bench]]
name = "ecdsa_verify"
harness = false

[[bench]]
name = "rfc6979_generate_k"
harness = false

