[package]
name = "starknet-crypto-codegen"
version = "0.1.0"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/xJonathanLEI/starknet-rs"
homepage = "https://starknet.rs/"
description = """
Codegen macros for `starknet-crypto`
"""
keywords = ["ethereum", "starknet", "web3"]

[lib]
proc-macro = true

[dependencies]
starknet-curve = { version = "0.1.0", path = "../starknet-curve" }
starknet-ff = { version = "0.2.0", path = "../starknet-ff" }
syn = "1.0.96"
no-std-compat = { version = "0.4.1", features = [
    "alloc",
    "compat_macros",
    "std",
] }
[features]
default = [ "std" ] # Default to using the std
std = [ "no-std-compat/std" ]